// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using picamerasserver.Database;

#nullable disable

namespace picamerasserver.Database.Migrations
{
    [DbContext(typeof(PiDbContext))]
    [Migration("20250801155435_IncreaseEnumLength")]
    partial class IncreaseEnumLength
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("picamerasserver.Database.Models.CameraModel", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.ToTable("Cameras");
                });

            modelBuilder.Entity("picamerasserver.Database.Models.CameraPictureModel", b =>
                {
                    b.Property<string>("CameraId")
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .IsFixedLength();

                    b.Property<Guid>("PictureRequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("CameraPictureStatus")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset?>("PictureTaken")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ReceivedSaved")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ReceivedSent")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ReceivedTaken")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StatusMessage")
                        .HasColumnType("text");

                    b.HasKey("CameraId", "PictureRequestId");

                    b.HasIndex("PictureRequestId");

                    b.ToTable("CameraPictures");
                });

            modelBuilder.Entity("picamerasserver.Database.Models.PictureRequestModel", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("PictureTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("RequestTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Uuid");

                    b.ToTable("PictureRequests");
                });

            modelBuilder.Entity("picamerasserver.Database.Models.CameraPictureModel", b =>
                {
                    b.HasOne("picamerasserver.Database.Models.CameraModel", "Camera")
                        .WithMany()
                        .HasForeignKey("CameraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("picamerasserver.Database.Models.PictureRequestModel", "PictureRequest")
                        .WithMany("CameraPictures")
                        .HasForeignKey("PictureRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Camera");

                    b.Navigation("PictureRequest");
                });

            modelBuilder.Entity("picamerasserver.Database.Models.PictureRequestModel", b =>
                {
                    b.Navigation("CameraPictures");
                });
#pragma warning restore 612, 618
        }
    }
}
